"use server";

import { openai } from "@ai-sdk/openai";
import { xai } from "@ai-sdk/xai";
import { createOpenRouter } from "@openrouter/ai-sdk-provider";
import { ModelMessage, experimental_generateImage, generateText } from "ai";
import logger from "logger";

type GenerateImageOptions = {
  messages?: ModelMessage[];
  prompt: string;
  abortSignal?: AbortSignal;
};

type GeneratedImage = {
  base64: string;
  mimeType?: string;
};

export type GeneratedImageResult = {
  images: GeneratedImage[];
};

export async function generateImageWithOpenAI(
  options: GenerateImageOptions,
): Promise<GeneratedImageResult> {
  return experimental_generateImage({
    model: openai.image("gpt-image-1-mini"),
    abortSignal: options.abortSignal,
    prompt: options.prompt,
  }).then((res) => {
    return {
      images: res.images.map((v) => {
        const item: GeneratedImage = {
          base64: Buffer.from(v.uint8Array).toString("base64"),
          mimeType: v.mediaType,
        };
        return item;
      }),
    };
  });
}

export async function generateImageWithXAI(
  options: GenerateImageOptions,
): Promise<GeneratedImageResult> {
  return experimental_generateImage({
    model: xai.image("grok-2-image"),
    abortSignal: options.abortSignal,
    prompt: options.prompt,
  }).then((res) => {
    return {
      images: res.images.map((v) => ({
        base64: Buffer.from(v.uint8Array).toString("base64"),
        mimeType: v.mediaType,
      })),
    };
  });
}

export const generateImageWithNanoBanana = async (
  options: GenerateImageOptions,
): Promise<GeneratedImageResult> => {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    throw new Error("OPENROUTER_API_KEY is not set");
  }

  const openrouter = createOpenRouter({ apiKey });

  const messages: ModelMessage[] = [...(options.messages ?? [])];
  if (options.prompt) {
    messages.push({
      role: "user",
      content: options.prompt,
    });
  }

  const response = await generateText({
    model: openrouter.chat("google/gemini-2.5-flash-image"),
    messages,
    abortSignal: options.abortSignal,
    providerOptions: {
      openrouter: {
        modalities: ["image", "text"],
      },
    },
  }).catch((err) => {
    logger.error(err);
    throw err;
  });

  const files = response.files ?? [];
  const images = files
    .filter((file) => file.mediaType?.startsWith("image/"))
    .map((file) => ({
      base64:
        file.base64 ??
        (file.uint8Array
          ? Buffer.from(file.uint8Array).toString("base64")
          : ""),
      mimeType: file.mediaType,
    }))
    .filter((image) => image.base64.length > 0);

  if (images.length === 0) {
    throw new Error("No images generated by the model");
  }

  return { images };
};
